# EMBERFALL: 1940 — audio.gd
# A small pool of positional players fed by the procedurally generated WAVs
# in sounds/ (pure-python wave synth — same trick as Faction Wars).
#
# Both pools run on the SFX bus. The vol_db arguments below are per-sound mixing
# — how loud a klaxon is against a rifle — and are unrelated to the SFX fader,
# which moves the whole bus underneath them.

class_name EFAudio
extends Node3D

const NAMES := ["shot_bullet", "shot_cannon", "shot_flak", "shot_rocket",
	"arc_zap", "expl_small", "expl_big", "sw_klaxon", "sw_boom", "place",
	"ready_chime", "salvage", "victory", "defeat",
	# deployment sounds — what rolled out, told by ear
	"dep_infantry", "dep_vehicle", "dep_air", "dep_harvester", "dep_arc",
	"dep_super", "dep_crawler"]

var streams := {}
var _pool: Array[AudioStreamPlayer3D] = []
var _ui_pool: Array[AudioStreamPlayer] = []
var _pi := 0
var _ui := 0


func _ready() -> void:
	for n in NAMES:
		var path := "res://sounds/%s.wav" % n
		if ResourceLoader.exists(path):
			streams[n] = load(path)
	for i in range(12):
		var p := AudioStreamPlayer3D.new()
		p.max_distance = 140.0
		p.unit_size = 14.0
		p.bus = EFSettings.BUS_SFX
		add_child(p)
		_pool.append(p)
	for i in range(3):
		var u := AudioStreamPlayer.new()
		u.bus = EFSettings.BUS_SFX
		add_child(u)
		_ui_pool.append(u)


func play(sound: String, pos: Vector3, vol_db := 0.0) -> void:
	if not streams.has(sound):
		return
	var p := _pool[_pi]
	_pi = (_pi + 1) % _pool.size()
	p.stream = streams[sound]
	p.global_position = pos
	p.volume_db = vol_db
	p.play()


func play_ui(sound: String, vol_db := 0.0) -> void:
	if not streams.has(sound):
		return
	var u := _ui_pool[_ui]
	_ui = (_ui + 1) % _ui_pool.size()
	u.stream = streams[sound]
	u.volume_db = vol_db
	u.play()


# ============================ THE ANNOUNCER ==================================
# One voice per banner (Kokoro TTS, generated by tools/make_announcer.py): the
# player hears their OWN side's command net, so the voice is faction identity
# the same way the palette is. Design rules learned from Red Alert's EVA:
#   - never overlap lines: one player, ONE held line, later requests drop
#   - per-event cooldowns, or "unit lost" narrates a massacre word by word
#   - the big three (superweapon, victory, defeat) interrupt whatever is up
# announce() is a safe no-op for any line whose wav is missing, so the game
# runs identically before the voice pack is generated.

const ANN_EVENTS := ["construction", "unit_ready", "base_attack", "low_power",
	"no_funds", "unit_lost", "sw_ready", "sw_launch", "victory", "defeat"]
const ANN_COOLDOWN := {"base_attack": 18.0, "unit_lost": 9.0, "low_power": 30.0,
	"no_funds": 15.0, "construction": 1.5, "unit_ready": 1.5}

var announcer_fac := 1
var _ann_player: AudioStreamPlayer = null
var _ann_cache := {}
var _ann_until := {}
var _ann_next := ""


func announce(event: String, force := false) -> void:
	var path := "res://sounds/ann/f%d_%s.wav" % [announcer_fac, event]
	if not _ann_cache.has(path):
		_ann_cache[path] = load(path) if ResourceLoader.exists(path) else null
	var stream: AudioStream = _ann_cache[path]
	if stream == null:
		return
	var now := Time.get_ticks_msec() / 1000.0
	if not force and now < float(_ann_until.get(event, 0.0)):
		return
	_ann_until[event] = now + float(ANN_COOLDOWN.get(event, 4.0))
	if _ann_player == null:
		_ann_player = AudioStreamPlayer.new()
		_ann_player.bus = EFSettings.BUS_SFX
		_ann_player.volume_db = 1.5
		add_child(_ann_player)
	if _ann_player.playing:
		if force:
			_ann_player.stop()
		else:
			_ann_next = path
			return
	_ann_player.stream = stream
	_ann_player.play()


func _process(_dt: float) -> void:
	if _ann_next != "" and _ann_player != null and not _ann_player.playing:
		var s2: AudioStream = _ann_cache.get(_ann_next)
		_ann_next = ""
		if s2 != null:
			_ann_player.stream = s2
			_ann_player.play()
